spring.application.name=project-management-system
spring.main.allow-circular-references=true

spring.datasource.url=jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:project_management_system}
spring.datasource.username=${PGUSER:${DB_USERNAME:postgres}}
spring.datasource.password=${PGPASSWORD:${DB_PASSWORD:postgres}}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

jwt.secret.key=${JWT_SECRET_KEY}
jwt.expiration.minutes=1440

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.enabled=true

aws.accessKeyId=${AWS_ACCESS_KEY_ID}
aws.secretKey=${AWS_SECRET_ACCESS_KEY}
aws.region=${AWS_REGION}
aws.bucket.name=${S3_BUCKET_NAME}

spring.mail.username=${EMAIL_USERNAME}

app.frontend.url=${FRONTEND_URL}

sendgrid.api.key=${SENDGRID_API_KEY:}
